site_name: Leda
theme: flatly

pages: 
  - Home: 'index.md'
  - Excel: 'excel.md'
  - Mercado financeiro / CPA-20: 'mercado-financeiro.md'
  - Python: 'python.md'
  - Dissertação: 'dissertacao.md'
  - SQL: 'sql.md'
